### PR TITLE
Add an analytics page

### PR DESCRIPTION
**Pull request by skapeyi**
# Adds analytics to data
1. I've created a new file. `analytics.html`
1. I read the data file and run analytics by gender, status and holding location.

## To test
At the bottom where there's privacy policy, click on the analytics link.
You'll also be able to navigate back to the home page from the analytics page

Expect to see something like this
Screenshot 2024-07-23 at 20 36 32

### CODE REVIEW

**Comment by Musacoli** [comment]
Hi @skapeyi 
There are some conflicts to resolve

**Comment by skapeyi** [comment]
> Hi @skapeyi There are some conflicts to resolve
Screenshot 2024-07-23 at 16 51 53

**Comment by wkambale** [comment]
this PR still has conflicts to resolve

**Comment by skapeyi** [comment]
> this PR still has conflicts to resolve

@wkambale resolved

**Review by Musacoli — APPROVED** [review]

**Pull request merged**
