### PR TITLE
Add contribute badge

### PR DESCRIPTION
**Pull request by kawerewagaba**
## Adds a contribute badge

Makes it easier to find the repo.
- Made some semantic changes to the markup (nothing fancy).
- Added the contribute badge that opens Github in a new tab.

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Testing Checklist

- [x] My changes generate no new warnings

## Screenshots / Recordings (if applicable)

Screenshot 2024-07-25 000733

### CODE REVIEW

**Review by Musacoli — COMMENTED** [review]
Nice work @kawerewagaba 
Looks good to me, I just think the contribute button might be better in the footer, rather than main header, given at the moment it's more a technical thing.

Let me know what you think.

**Comment by kawerewagaba** [comment]
Right. Thought about that too - but seeing that the product is currently in rapid development, I felt the need to have quick access to the repo for anyone looking, without having to scroll through the growing list of people.

Of course this can be changed (later) but it doesn't hurt to take up the branding spot - since there is currently no branding available.

The other upside of that spot is that it speaks to the openness of the project (just thinking) but I don't mind taking your guidance on this.

**Comment by Musacoli** [comment]
> Right. Thought about that too - but seeing that the product is currently in rapid development, I felt the need to have quick access to the repo for anyone looking, without having to scroll through the growing list of people.
> 
> Of course this can be changed (later) but it doesn't hurt to take up the branding spot - since there is currently no branding available.
> 
> The other upside of that spot is that it speaks to the openness of the project (just thinking) but I don't mind taking your guidance on this.

I honestly have no strong opinion about it, I think my concern is more around the discreetness that comes with it being at the footer and primarily findable by devs mostly, which is safer but on second thought, the repo is already out there, so maybe I am over thinking this.

**Review by Musacoli — APPROVED** [review]

**Comment by Musacoli** [comment]
Reverting this for now, as it looks like it broke the website.

Screenshot 2024-07-25 at 1 28 03 AM

**Comment by kawerewagaba** [comment]
> Reverting this for now, as it looks like it broke the website.
> 
> Screenshot 2024-07-25 at 1 28 03 AM

Going to deploy the branch on the side (remotely) to try and reproduce this - my guess is it could have been a caching issue on your end? I believe it is also a good time to setup a `staging` environment.

**Comment by Musacoli** [comment]
> > Reverting this for now, as it looks like it broke the website.
> > Screenshot 2024-07-25 at 1 28 03 AM
> 
> Going to deploy the branch on the side (remotely) to try and reproduce this - my guess is it could have been a caching issue on your end? I believe it is also a good time to setup a `staging` environment.

100%, I did try clearing cache though a couple of times, but let me know if you're able to get it as well.

**Pull request merged**
