### PR TITLE
#Integrate data received from the API

### PR DESCRIPTION
**Pull request by armstrongsouljah**
## Description
- Integrates API data as opposed to previously loading from the `data.json` file.
Please include a summary of the changes and the related issue(s) this PR addresses.
- Fixed the following issue or added a new feature

Fixes #(93)

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Testing Checklist

- [ ] My changes generate no new warnings

## Screenshots / Recordings (if applicable)

Please add any screenshots that demonstrate the changes made.

### CODE REVIEW

**Comment by Musacoli** [comment]
Looks good, but we'll need to make sure infinite scroll works before merging this to prod.
Currently it only loads the 15 names then stops there.

**Comment by armstrongsouljah** [comment]
> Looks good, but we'll need to make sure infinite scroll works before merging this to prod.
> Currently it only loads the 15 names then stops there.

Is someone available to spawn off this branch and re-enable infinite scroll?

**Comment by skapeyi** [comment]
@armstrongsouljah the analytics page, is also currently using the data.json file. Can you please update it to pull the data from the API endpoint? So we hit two birds with one stone?

**Comment by armstrongsouljah** [comment]
> Is someone available to spawn off this branch and re-enable infinite scroll?

This has been updated.

**Review by Musacoli — APPROVED** [review]
LGTM

**Pull request merged**
