### PR TITLE
Infinite scroll

### PR DESCRIPTION
**Pull request by nelson1995**
Added infinite scroll for better display of results.

### CODE REVIEW

**Comment by kaybrian** [comment]
sorry i am seeing conflicts, could you please resolve these

**Comment by Musacoli** [comment]
@nelson1995 could you address the conflicts here

**Comment by Musacoli** [comment]
If possible could you also add a screenshot or screen recording of the new change

**Comment by nelson1995** [comment]
> @nelson1995 could you address the conflicts here
> 
> Another thing I've noticed is I don't see the effects of the infinite scroll, either because of minimal data or its just really fast which wouldn't be bad.

Thanks for the info and my apologies. I've fixed the infinite scroll and adjusted the spinner speed. Kindly merge the new pr. Thanks.

**Pull request merged**
