### PR TITLE
Added a Marquee

### PR DESCRIPTION
**Pull request by Kubomu**
"Defending Freedom: Exposing Unjust Detentions"

### CODE REVIEW

**Comment by wkambale** [comment]
your PR has conflicts. please resolve them.

**Comment by Kubomu** [comment]
Wanted to add a Marquee on the index.html.

**Comment by Slam256** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/marquee marquee are a deprecated component

**Comment by Kubomu** [comment]
Thanks

**Comment by skapeyi** [comment]
@Kubomu given @Slam256 's feedback, I suggest we close this PR. 
@Slam256 if you are happy with the suggestion, please close the PR.

**Pull request closed without merging**
